import stylish from '@dmamills/stylish';

export const [ 
  flex,
  alignItemsCenter,
  flexCenter,
  column,
  spacedEvenly,
  spaceBetween,
  justifyEnd,
  flexGrow,
  flex2,
  textCenter,
  listStyleNone,
  p1,
  p05,
  p0,
  m0,
  debugBox,
 ] = stylish(
  { display: 'flex' },
  { alignItems: 'center' },
  { alignItems: 'center', justifyContent: 'center' },
  { flexDirection: 'column' },
  { justifyContent: 'space-evenly' },
  { justifyContent: 'space-between' },
  { justifyContent: 'flex-end' },
  { flexGrow: '1' },
  { flex: '2' },
  { textAlign: 'center' },
  { listStyleType: 'none' },
  { padding: '1rem' },
  { padding: '0.5rem' },
  { padding: '0' },
  { margin: '0' },
  { border: '1px solid black' },
);


export default {
  flex,
  alignItemsCenter,
  flexCenter,
  column,
  spacedEvenly,
  spaceBetween,
  justifyEnd,
  flexGrow,
  flex2,
  textCenter,
  p1,
  p05,
  m0,
  p0,
  listStyleNone,
  debugBox,
}
